// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sanxemmloxomhugvtncy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNhbnhlbW1sb3hvbWh1Z3Z0bmN5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQwMTk5MjAsImV4cCI6MjA1OTU5NTkyMH0.6h2bQ-h7B5QeImH09CluDxbxPwv57qV8p08dOnUz6Z8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);